title: وبلاگ صدرا املشی
email: sadra@isapanah.com
description: > # this means to ignore newlines until "baseurl:"
 سلام! من صدرا عیسی پناه املشی هستم. توسعه دهنده اپلیکیشن iOS و Android.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://isapanah.com" # the base hostname & protocol for your site, e.g. http://example.com

twitter_path: https://twitter.com/sadra-amlashi
github_path: https://github.com/sadra
facebook_path: https://facebook.com/sadra.am123
medium_path: https://medium.com/sadra
linkedin_path: https://www.linkedin.com/in/amlashisadra/

# Build settings
permalink: :year/:title
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-autoprefixer
  - jekyll-archives
  - jalalidate
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
  style: compressed

jekyll-archives:
  enabled:
    - tags
    - categories
  layouts:
    tag: tag-archive
    category: category-archive
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'
include:
  - .nojekyll
  - .htaccess

notfound404-cover: /assets/img/base/bugart-bacall.jpg

collections:
  screencast:
    output: true
    permalink: "video/:collection/:title/"
  course:
    output: true
    permalink: "video/:collection/:categories/:title/"
